name = "ai-study-calendar"
compatibility_date = "2026-10-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ai-study-calendar-db"
database_id = "b8aa6233-aff4-4aaf-a21f-8b2d98c92a07"
